version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    environment:
      - REDIS_HOST=redis # redis here refers to the redis image above
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/src/app/node_modules
      - ./worker:/usr/src/app
    environment:
      - REDIS_HOST=redis # redis here refers to the redis image above
      - REDIS_PORT=6379
    depends_on:
      - redis
